// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: oauthcredentials/v1/oauth.proto

package oauthcredentials

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListOAuthsForOwnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Page  *int32 `protobuf:"varint,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Limit *int32 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
}

func (x *ListOAuthsForOwnerRequest) Reset() {
	*x = ListOAuthsForOwnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oauthcredentials_v1_oauth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOAuthsForOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOAuthsForOwnerRequest) ProtoMessage() {}

func (x *ListOAuthsForOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauthcredentials_v1_oauth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOAuthsForOwnerRequest.ProtoReflect.Descriptor instead.
func (*ListOAuthsForOwnerRequest) Descriptor() ([]byte, []int) {
	return file_oauthcredentials_v1_oauth_proto_rawDescGZIP(), []int{0}
}

func (x *ListOAuthsForOwnerRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ListOAuthsForOwnerRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListOAuthsForOwnerRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type ListOAuthsForOwnerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OauthApps []*OAuthApp `protobuf:"bytes,1,rep,name=oauth_apps,json=oauthApps,proto3" json:"oauth_apps,omitempty"`
}

func (x *ListOAuthsForOwnerResponse) Reset() {
	*x = ListOAuthsForOwnerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oauthcredentials_v1_oauth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOAuthsForOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOAuthsForOwnerResponse) ProtoMessage() {}

func (x *ListOAuthsForOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oauthcredentials_v1_oauth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOAuthsForOwnerResponse.ProtoReflect.Descriptor instead.
func (*ListOAuthsForOwnerResponse) Descriptor() ([]byte, []int) {
	return file_oauthcredentials_v1_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *ListOAuthsForOwnerResponse) GetOauthApps() []*OAuthApp {
	if x != nil {
		return x.OauthApps
	}
	return nil
}

type GetOAuthByProviderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner    string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
}

func (x *GetOAuthByProviderRequest) Reset() {
	*x = GetOAuthByProviderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oauthcredentials_v1_oauth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOAuthByProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthByProviderRequest) ProtoMessage() {}

func (x *GetOAuthByProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauthcredentials_v1_oauth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuthByProviderRequest.ProtoReflect.Descriptor instead.
func (*GetOAuthByProviderRequest) Descriptor() ([]byte, []int) {
	return file_oauthcredentials_v1_oauth_proto_rawDescGZIP(), []int{2}
}

func (x *GetOAuthByProviderRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetOAuthByProviderRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type GetOAuthByProviderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OauthApp *OAuthApp `protobuf:"bytes,1,opt,name=oauth_app,json=oauthApp,proto3" json:"oauth_app,omitempty"`
}

func (x *GetOAuthByProviderResponse) Reset() {
	*x = GetOAuthByProviderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oauthcredentials_v1_oauth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOAuthByProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthByProviderResponse) ProtoMessage() {}

func (x *GetOAuthByProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oauthcredentials_v1_oauth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuthByProviderResponse.ProtoReflect.Descriptor instead.
func (*GetOAuthByProviderResponse) Descriptor() ([]byte, []int) {
	return file_oauthcredentials_v1_oauth_proto_rawDescGZIP(), []int{3}
}

func (x *GetOAuthByProviderResponse) GetOauthApp() *OAuthApp {
	if x != nil {
		return x.OauthApp
	}
	return nil
}

type GetOAuthCredentialByProviderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner    string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
}

func (x *GetOAuthCredentialByProviderRequest) Reset() {
	*x = GetOAuthCredentialByProviderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oauthcredentials_v1_oauth_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOAuthCredentialByProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthCredentialByProviderRequest) ProtoMessage() {}

func (x *GetOAuthCredentialByProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauthcredentials_v1_oauth_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuthCredentialByProviderRequest.ProtoReflect.Descriptor instead.
func (*GetOAuthCredentialByProviderRequest) Descriptor() ([]byte, []int) {
	return file_oauthcredentials_v1_oauth_proto_rawDescGZIP(), []int{4}
}

func (x *GetOAuthCredentialByProviderRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetOAuthCredentialByProviderRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type GetOAuthCredentialByProviderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *GetOAuthCredentialByProviderResponse) Reset() {
	*x = GetOAuthCredentialByProviderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oauthcredentials_v1_oauth_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOAuthCredentialByProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthCredentialByProviderResponse) ProtoMessage() {}

func (x *GetOAuthCredentialByProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oauthcredentials_v1_oauth_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuthCredentialByProviderResponse.ProtoReflect.Descriptor instead.
func (*GetOAuthCredentialByProviderResponse) Descriptor() ([]byte, []int) {
	return file_oauthcredentials_v1_oauth_proto_rawDescGZIP(), []int{5}
}

func (x *GetOAuthCredentialByProviderResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type OAuthTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner       string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Provider    string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Code        string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	RedirectUri string `protobuf:"bytes,4,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
}

func (x *OAuthTokenRequest) Reset() {
	*x = OAuthTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oauthcredentials_v1_oauth_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OAuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthTokenRequest) ProtoMessage() {}

func (x *OAuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauthcredentials_v1_oauth_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthTokenRequest.ProtoReflect.Descriptor instead.
func (*OAuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_oauthcredentials_v1_oauth_proto_rawDescGZIP(), []int{6}
}

func (x *OAuthTokenRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *OAuthTokenRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OAuthTokenRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OAuthTokenRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type OAuthApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner    string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Provider string   `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Scopes   []string `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
}

func (x *OAuthApp) Reset() {
	*x = OAuthApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oauthcredentials_v1_oauth_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OAuthApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthApp) ProtoMessage() {}

func (x *OAuthApp) ProtoReflect() protoreflect.Message {
	mi := &file_oauthcredentials_v1_oauth_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthApp.ProtoReflect.Descriptor instead.
func (*OAuthApp) Descriptor() ([]byte, []int) {
	return file_oauthcredentials_v1_oauth_proto_rawDescGZIP(), []int{7}
}

func (x *OAuthApp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OAuthApp) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *OAuthApp) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OAuthApp) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

var File_oauthcredentials_v1_oauth_proto protoreflect.FileDescriptor

var file_oauthcredentials_v1_oauth_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x13, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x78, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x41,
	0x75, 0x74, 0x68, 0x73, 0x46, 0x6f, 0x72, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x01, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x22, 0x5a, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x73, 0x46, 0x6f,
	0x72, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c,
	0x0a, 0x0a, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x61, 0x70, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x41, 0x70,
	0x70, 0x52, 0x09, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x41, 0x70, 0x70, 0x73, 0x22, 0x4d, 0x0a, 0x19,
	0x47, 0x65, 0x74, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0x58, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x6f, 0x61, 0x75,
	0x74, 0x68, 0x5f, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f,
	0x61, 0x75, 0x74, 0x68, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x41, 0x70, 0x70, 0x52, 0x08, 0x6f, 0x61, 0x75,
	0x74, 0x68, 0x41, 0x70, 0x70, 0x22, 0x57, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x4f, 0x41, 0x75, 0x74,
	0x68, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x42, 0x79, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0x49,
	0x0a, 0x24, 0x47, 0x65, 0x74, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x7c, 0x0a, 0x11, 0x4f, 0x41, 0x75,
	0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x5f, 0x75, 0x72, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x69, 0x22, 0x64, 0x0a, 0x08, 0x4f, 0x41, 0x75, 0x74, 0x68,
	0x41, 0x70, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x32, 0x98, 0x03,
	0x0a, 0x0c, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x77,
	0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x73, 0x46, 0x6f, 0x72, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x12, 0x2e, 0x2e, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x63, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x41, 0x75, 0x74, 0x68, 0x73, 0x46, 0x6f, 0x72, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x63, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x41, 0x75, 0x74, 0x68, 0x73, 0x46, 0x6f, 0x72, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x77, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4f, 0x41,
	0x75, 0x74, 0x68, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x2e, 0x2e,
	0x6f, 0x61, 0x75, 0x74, 0x68, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x42, 0x79, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e,
	0x6f, 0x61, 0x75, 0x74, 0x68, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x42, 0x79, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x95, 0x01, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x12, 0x38, 0x2e, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x41, 0x75, 0x74, 0x68,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x39, 0x2e, 0x6f, 0x61,
	0x75, 0x74, 0x68, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x61, 0x5a, 0x5f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76,
	0x2d, 0x69, 0x6f, 0x2f, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x2d, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x63, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x6f, 0x61, 0x75, 0x74, 0x68,
	0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_oauthcredentials_v1_oauth_proto_rawDescOnce sync.Once
	file_oauthcredentials_v1_oauth_proto_rawDescData = file_oauthcredentials_v1_oauth_proto_rawDesc
)

func file_oauthcredentials_v1_oauth_proto_rawDescGZIP() []byte {
	file_oauthcredentials_v1_oauth_proto_rawDescOnce.Do(func() {
		file_oauthcredentials_v1_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(file_oauthcredentials_v1_oauth_proto_rawDescData)
	})
	return file_oauthcredentials_v1_oauth_proto_rawDescData
}

var file_oauthcredentials_v1_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_oauthcredentials_v1_oauth_proto_goTypes = []interface{}{
	(*ListOAuthsForOwnerRequest)(nil),            // 0: oauthcredentials.v1.ListOAuthsForOwnerRequest
	(*ListOAuthsForOwnerResponse)(nil),           // 1: oauthcredentials.v1.ListOAuthsForOwnerResponse
	(*GetOAuthByProviderRequest)(nil),            // 2: oauthcredentials.v1.GetOAuthByProviderRequest
	(*GetOAuthByProviderResponse)(nil),           // 3: oauthcredentials.v1.GetOAuthByProviderResponse
	(*GetOAuthCredentialByProviderRequest)(nil),  // 4: oauthcredentials.v1.GetOAuthCredentialByProviderRequest
	(*GetOAuthCredentialByProviderResponse)(nil), // 5: oauthcredentials.v1.GetOAuthCredentialByProviderResponse
	(*OAuthTokenRequest)(nil),                    // 6: oauthcredentials.v1.OAuthTokenRequest
	(*OAuthApp)(nil),                             // 7: oauthcredentials.v1.OAuthApp
}
var file_oauthcredentials_v1_oauth_proto_depIdxs = []int32{
	7, // 0: oauthcredentials.v1.ListOAuthsForOwnerResponse.oauth_apps:type_name -> oauthcredentials.v1.OAuthApp
	7, // 1: oauthcredentials.v1.GetOAuthByProviderResponse.oauth_app:type_name -> oauthcredentials.v1.OAuthApp
	0, // 2: oauthcredentials.v1.OAuthService.ListOAuthsForOwner:input_type -> oauthcredentials.v1.ListOAuthsForOwnerRequest
	2, // 3: oauthcredentials.v1.OAuthService.GetOAuthByProvider:input_type -> oauthcredentials.v1.GetOAuthByProviderRequest
	4, // 4: oauthcredentials.v1.OAuthService.GetOAuthCredentialByProvider:input_type -> oauthcredentials.v1.GetOAuthCredentialByProviderRequest
	1, // 5: oauthcredentials.v1.OAuthService.ListOAuthsForOwner:output_type -> oauthcredentials.v1.ListOAuthsForOwnerResponse
	3, // 6: oauthcredentials.v1.OAuthService.GetOAuthByProvider:output_type -> oauthcredentials.v1.GetOAuthByProviderResponse
	5, // 7: oauthcredentials.v1.OAuthService.GetOAuthCredentialByProvider:output_type -> oauthcredentials.v1.GetOAuthCredentialByProviderResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_oauthcredentials_v1_oauth_proto_init() }
func file_oauthcredentials_v1_oauth_proto_init() {
	if File_oauthcredentials_v1_oauth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_oauthcredentials_v1_oauth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOAuthsForOwnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oauthcredentials_v1_oauth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOAuthsForOwnerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oauthcredentials_v1_oauth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOAuthByProviderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oauthcredentials_v1_oauth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOAuthByProviderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oauthcredentials_v1_oauth_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOAuthCredentialByProviderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oauthcredentials_v1_oauth_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOAuthCredentialByProviderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oauthcredentials_v1_oauth_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OAuthTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oauthcredentials_v1_oauth_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OAuthApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_oauthcredentials_v1_oauth_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oauthcredentials_v1_oauth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oauthcredentials_v1_oauth_proto_goTypes,
		DependencyIndexes: file_oauthcredentials_v1_oauth_proto_depIdxs,
		MessageInfos:      file_oauthcredentials_v1_oauth_proto_msgTypes,
	}.Build()
	File_oauthcredentials_v1_oauth_proto = out.File
	file_oauthcredentials_v1_oauth_proto_rawDesc = nil
	file_oauthcredentials_v1_oauth_proto_goTypes = nil
	file_oauthcredentials_v1_oauth_proto_depIdxs = nil
}
