// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: oauthcredentials/v1/provider.proto

package oauthcredentials

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OAuthProviderServiceClient is the client API for OAuthProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OAuthProviderServiceClient interface {
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (OAuthProviderService_ListProvidersClient, error)
	CreateProvider(ctx context.Context, in *CreateProviderRequest, opts ...grpc.CallOption) (*CreateProviderResponse, error)
	UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...grpc.CallOption) (*UpdateProviderResponse, error)
	DeleteProvider(ctx context.Context, in *DeleteProviderRequest, opts ...grpc.CallOption) (*DeleteProviderResponse, error)
	ExchangeAuthorizationCode(ctx context.Context, in *ExchangeAuthorizationCodeRequest, opts ...grpc.CallOption) (*ExchangeAuthorizationCodeResponse, error)
}

type oAuthProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOAuthProviderServiceClient(cc grpc.ClientConnInterface) OAuthProviderServiceClient {
	return &oAuthProviderServiceClient{cc}
}

func (c *oAuthProviderServiceClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (OAuthProviderService_ListProvidersClient, error) {
	stream, err := c.cc.NewStream(ctx, &OAuthProviderService_ServiceDesc.Streams[0], "/oauthcredentials.v1.OAuthProviderService/ListProviders", opts...)
	if err != nil {
		return nil, err
	}
	x := &oAuthProviderServiceListProvidersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OAuthProviderService_ListProvidersClient interface {
	Recv() (*ListProvidersResponse, error)
	grpc.ClientStream
}

type oAuthProviderServiceListProvidersClient struct {
	grpc.ClientStream
}

func (x *oAuthProviderServiceListProvidersClient) Recv() (*ListProvidersResponse, error) {
	m := new(ListProvidersResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *oAuthProviderServiceClient) CreateProvider(ctx context.Context, in *CreateProviderRequest, opts ...grpc.CallOption) (*CreateProviderResponse, error) {
	out := new(CreateProviderResponse)
	err := c.cc.Invoke(ctx, "/oauthcredentials.v1.OAuthProviderService/CreateProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthProviderServiceClient) UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...grpc.CallOption) (*UpdateProviderResponse, error) {
	out := new(UpdateProviderResponse)
	err := c.cc.Invoke(ctx, "/oauthcredentials.v1.OAuthProviderService/UpdateProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthProviderServiceClient) DeleteProvider(ctx context.Context, in *DeleteProviderRequest, opts ...grpc.CallOption) (*DeleteProviderResponse, error) {
	out := new(DeleteProviderResponse)
	err := c.cc.Invoke(ctx, "/oauthcredentials.v1.OAuthProviderService/DeleteProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthProviderServiceClient) ExchangeAuthorizationCode(ctx context.Context, in *ExchangeAuthorizationCodeRequest, opts ...grpc.CallOption) (*ExchangeAuthorizationCodeResponse, error) {
	out := new(ExchangeAuthorizationCodeResponse)
	err := c.cc.Invoke(ctx, "/oauthcredentials.v1.OAuthProviderService/ExchangeAuthorizationCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OAuthProviderServiceServer is the server API for OAuthProviderService service.
// All implementations must embed UnimplementedOAuthProviderServiceServer
// for forward compatibility
type OAuthProviderServiceServer interface {
	ListProviders(*ListProvidersRequest, OAuthProviderService_ListProvidersServer) error
	CreateProvider(context.Context, *CreateProviderRequest) (*CreateProviderResponse, error)
	UpdateProvider(context.Context, *UpdateProviderRequest) (*UpdateProviderResponse, error)
	DeleteProvider(context.Context, *DeleteProviderRequest) (*DeleteProviderResponse, error)
	ExchangeAuthorizationCode(context.Context, *ExchangeAuthorizationCodeRequest) (*ExchangeAuthorizationCodeResponse, error)
	mustEmbedUnimplementedOAuthProviderServiceServer()
}

// UnimplementedOAuthProviderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOAuthProviderServiceServer struct {
}

func (UnimplementedOAuthProviderServiceServer) ListProviders(*ListProvidersRequest, OAuthProviderService_ListProvidersServer) error {
	return status.Errorf(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedOAuthProviderServiceServer) CreateProvider(context.Context, *CreateProviderRequest) (*CreateProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProvider not implemented")
}
func (UnimplementedOAuthProviderServiceServer) UpdateProvider(context.Context, *UpdateProviderRequest) (*UpdateProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProvider not implemented")
}
func (UnimplementedOAuthProviderServiceServer) DeleteProvider(context.Context, *DeleteProviderRequest) (*DeleteProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProvider not implemented")
}
func (UnimplementedOAuthProviderServiceServer) ExchangeAuthorizationCode(context.Context, *ExchangeAuthorizationCodeRequest) (*ExchangeAuthorizationCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangeAuthorizationCode not implemented")
}
func (UnimplementedOAuthProviderServiceServer) mustEmbedUnimplementedOAuthProviderServiceServer() {}

// UnsafeOAuthProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OAuthProviderServiceServer will
// result in compilation errors.
type UnsafeOAuthProviderServiceServer interface {
	mustEmbedUnimplementedOAuthProviderServiceServer()
}

func RegisterOAuthProviderServiceServer(s grpc.ServiceRegistrar, srv OAuthProviderServiceServer) {
	s.RegisterService(&OAuthProviderService_ServiceDesc, srv)
}

func _OAuthProviderService_ListProviders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListProvidersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OAuthProviderServiceServer).ListProviders(m, &oAuthProviderServiceListProvidersServer{stream})
}

type OAuthProviderService_ListProvidersServer interface {
	Send(*ListProvidersResponse) error
	grpc.ServerStream
}

type oAuthProviderServiceListProvidersServer struct {
	grpc.ServerStream
}

func (x *oAuthProviderServiceListProvidersServer) Send(m *ListProvidersResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _OAuthProviderService_CreateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthProviderServiceServer).CreateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauthcredentials.v1.OAuthProviderService/CreateProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthProviderServiceServer).CreateProvider(ctx, req.(*CreateProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthProviderService_UpdateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthProviderServiceServer).UpdateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauthcredentials.v1.OAuthProviderService/UpdateProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthProviderServiceServer).UpdateProvider(ctx, req.(*UpdateProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthProviderService_DeleteProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthProviderServiceServer).DeleteProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauthcredentials.v1.OAuthProviderService/DeleteProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthProviderServiceServer).DeleteProvider(ctx, req.(*DeleteProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthProviderService_ExchangeAuthorizationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeAuthorizationCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthProviderServiceServer).ExchangeAuthorizationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oauthcredentials.v1.OAuthProviderService/ExchangeAuthorizationCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthProviderServiceServer).ExchangeAuthorizationCode(ctx, req.(*ExchangeAuthorizationCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OAuthProviderService_ServiceDesc is the grpc.ServiceDesc for OAuthProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OAuthProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oauthcredentials.v1.OAuthProviderService",
	HandlerType: (*OAuthProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProvider",
			Handler:    _OAuthProviderService_CreateProvider_Handler,
		},
		{
			MethodName: "UpdateProvider",
			Handler:    _OAuthProviderService_UpdateProvider_Handler,
		},
		{
			MethodName: "DeleteProvider",
			Handler:    _OAuthProviderService_DeleteProvider_Handler,
		},
		{
			MethodName: "ExchangeAuthorizationCode",
			Handler:    _OAuthProviderService_ExchangeAuthorizationCode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListProviders",
			Handler:       _OAuthProviderService_ListProviders_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "oauthcredentials/v1/provider.proto",
}
