// Code generated by mockery v2.44.1. DO NOT EDIT.

package oauthapp

import (
	context "context"

	modelsoauthapp "github.com/microserv-io/oauth2-token-vault/internal/domain/models/oauthapp"
	mock "github.com/stretchr/testify/mock"
	oauth2 "golang.org/x/oauth2"

	provider "github.com/microserv-io/oauth2-token-vault/internal/domain/models/provider"
)

// MockTokenSourceFactory is an autogenerated mock type for the TokenSourceFactory type
type MockTokenSourceFactory struct {
	mock.Mock
}

type MockTokenSourceFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenSourceFactory) EXPECT() *MockTokenSourceFactory_Expecter {
	return &MockTokenSourceFactory_Expecter{mock: &_m.Mock}
}

// NewTokenSource provides a mock function with given fields: ctx, _a1, oauthApp
func (_m *MockTokenSourceFactory) NewTokenSource(ctx context.Context, _a1 *provider.Provider, oauthApp *modelsoauthapp.OAuthApp) oauth2.TokenSource {
	ret := _m.Called(ctx, _a1, oauthApp)

	if len(ret) == 0 {
		panic("no return value specified for NewTokenSource")
	}

	var r0 oauth2.TokenSource
	if rf, ok := ret.Get(0).(func(context.Context, *provider.Provider, *modelsoauthapp.OAuthApp) oauth2.TokenSource); ok {
		r0 = rf(ctx, _a1, oauthApp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(oauth2.TokenSource)
		}
	}

	return r0
}

// MockTokenSourceFactory_NewTokenSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTokenSource'
type MockTokenSourceFactory_NewTokenSource_Call struct {
	*mock.Call
}

// NewTokenSource is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *provider.Provider
//   - oauthApp *modelsoauthapp.OAuthApp
func (_e *MockTokenSourceFactory_Expecter) NewTokenSource(ctx interface{}, _a1 interface{}, oauthApp interface{}) *MockTokenSourceFactory_NewTokenSource_Call {
	return &MockTokenSourceFactory_NewTokenSource_Call{Call: _e.mock.On("NewTokenSource", ctx, _a1, oauthApp)}
}

func (_c *MockTokenSourceFactory_NewTokenSource_Call) Run(run func(ctx context.Context, _a1 *provider.Provider, oauthApp *modelsoauthapp.OAuthApp)) *MockTokenSourceFactory_NewTokenSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*provider.Provider), args[2].(*modelsoauthapp.OAuthApp))
	})
	return _c
}

func (_c *MockTokenSourceFactory_NewTokenSource_Call) Return(_a0 oauth2.TokenSource) *MockTokenSourceFactory_NewTokenSource_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenSourceFactory_NewTokenSource_Call) RunAndReturn(run func(context.Context, *provider.Provider, *modelsoauthapp.OAuthApp) oauth2.TokenSource) *MockTokenSourceFactory_NewTokenSource_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenSourceFactory creates a new instance of MockTokenSourceFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenSourceFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenSourceFactory {
	mock := &MockTokenSourceFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
