// Code generated by mockery v2.44.1. DO NOT EDIT.

package oauthservice

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"

	oauthcredentials "github.com/microserv-io/oauth-credentials-server/pkg/proto/oauthcredentials/v1"
)

// MockListOAuthsStream is an autogenerated mock type for the ListOAuthsStream type
type MockListOAuthsStream struct {
	mock.Mock
}

type MockListOAuthsStream_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListOAuthsStream) EXPECT() *MockListOAuthsStream_Expecter {
	return &MockListOAuthsStream_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with given fields:
func (_m *MockListOAuthsStream) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// MockListOAuthsStream_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockListOAuthsStream_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockListOAuthsStream_Expecter) Context() *MockListOAuthsStream_Context_Call {
	return &MockListOAuthsStream_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockListOAuthsStream_Context_Call) Run(run func()) *MockListOAuthsStream_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockListOAuthsStream_Context_Call) Return(_a0 context.Context) *MockListOAuthsStream_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListOAuthsStream_Context_Call) RunAndReturn(run func() context.Context) *MockListOAuthsStream_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *MockListOAuthsStream) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListOAuthsStream_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockListOAuthsStream_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *MockListOAuthsStream_Expecter) RecvMsg(m interface{}) *MockListOAuthsStream_RecvMsg_Call {
	return &MockListOAuthsStream_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockListOAuthsStream_RecvMsg_Call) Run(run func(m interface{})) *MockListOAuthsStream_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockListOAuthsStream_RecvMsg_Call) Return(_a0 error) *MockListOAuthsStream_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListOAuthsStream_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *MockListOAuthsStream_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *MockListOAuthsStream) Send(_a0 *oauthcredentials.ListOAuthsResponse) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*oauthcredentials.ListOAuthsResponse) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListOAuthsStream_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockListOAuthsStream_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *oauthcredentials.ListOAuthsResponse
func (_e *MockListOAuthsStream_Expecter) Send(_a0 interface{}) *MockListOAuthsStream_Send_Call {
	return &MockListOAuthsStream_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *MockListOAuthsStream_Send_Call) Run(run func(_a0 *oauthcredentials.ListOAuthsResponse)) *MockListOAuthsStream_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*oauthcredentials.ListOAuthsResponse))
	})
	return _c
}

func (_c *MockListOAuthsStream_Send_Call) Return(_a0 error) *MockListOAuthsStream_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListOAuthsStream_Send_Call) RunAndReturn(run func(*oauthcredentials.ListOAuthsResponse) error) *MockListOAuthsStream_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *MockListOAuthsStream) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListOAuthsStream_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type MockListOAuthsStream_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockListOAuthsStream_Expecter) SendHeader(_a0 interface{}) *MockListOAuthsStream_SendHeader_Call {
	return &MockListOAuthsStream_SendHeader_Call{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *MockListOAuthsStream_SendHeader_Call) Run(run func(_a0 metadata.MD)) *MockListOAuthsStream_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockListOAuthsStream_SendHeader_Call) Return(_a0 error) *MockListOAuthsStream_SendHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListOAuthsStream_SendHeader_Call) RunAndReturn(run func(metadata.MD) error) *MockListOAuthsStream_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *MockListOAuthsStream) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListOAuthsStream_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockListOAuthsStream_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *MockListOAuthsStream_Expecter) SendMsg(m interface{}) *MockListOAuthsStream_SendMsg_Call {
	return &MockListOAuthsStream_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockListOAuthsStream_SendMsg_Call) Run(run func(m interface{})) *MockListOAuthsStream_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockListOAuthsStream_SendMsg_Call) Return(_a0 error) *MockListOAuthsStream_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListOAuthsStream_SendMsg_Call) RunAndReturn(run func(interface{}) error) *MockListOAuthsStream_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *MockListOAuthsStream) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListOAuthsStream_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockListOAuthsStream_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockListOAuthsStream_Expecter) SetHeader(_a0 interface{}) *MockListOAuthsStream_SetHeader_Call {
	return &MockListOAuthsStream_SetHeader_Call{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *MockListOAuthsStream_SetHeader_Call) Run(run func(_a0 metadata.MD)) *MockListOAuthsStream_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockListOAuthsStream_SetHeader_Call) Return(_a0 error) *MockListOAuthsStream_SetHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListOAuthsStream_SetHeader_Call) RunAndReturn(run func(metadata.MD) error) *MockListOAuthsStream_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *MockListOAuthsStream) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// MockListOAuthsStream_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type MockListOAuthsStream_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockListOAuthsStream_Expecter) SetTrailer(_a0 interface{}) *MockListOAuthsStream_SetTrailer_Call {
	return &MockListOAuthsStream_SetTrailer_Call{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *MockListOAuthsStream_SetTrailer_Call) Run(run func(_a0 metadata.MD)) *MockListOAuthsStream_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockListOAuthsStream_SetTrailer_Call) Return() *MockListOAuthsStream_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockListOAuthsStream_SetTrailer_Call) RunAndReturn(run func(metadata.MD)) *MockListOAuthsStream_SetTrailer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListOAuthsStream creates a new instance of MockListOAuthsStream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListOAuthsStream(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListOAuthsStream {
	mock := &MockListOAuthsStream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
