// Code generated by mockery v2.44.1. DO NOT EDIT.

package providerservice

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"

	oauthcredentials "github.com/microserv-io/oauth-credentials-server/pkg/proto/oauthcredentials/v1"
)

// MockListProviderStream is an autogenerated mock type for the ListProviderStream type
type MockListProviderStream struct {
	mock.Mock
}

type MockListProviderStream_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListProviderStream) EXPECT() *MockListProviderStream_Expecter {
	return &MockListProviderStream_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with given fields:
func (_m *MockListProviderStream) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// MockListProviderStream_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockListProviderStream_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockListProviderStream_Expecter) Context() *MockListProviderStream_Context_Call {
	return &MockListProviderStream_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockListProviderStream_Context_Call) Run(run func()) *MockListProviderStream_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockListProviderStream_Context_Call) Return(_a0 context.Context) *MockListProviderStream_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListProviderStream_Context_Call) RunAndReturn(run func() context.Context) *MockListProviderStream_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *MockListProviderStream) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListProviderStream_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockListProviderStream_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *MockListProviderStream_Expecter) RecvMsg(m interface{}) *MockListProviderStream_RecvMsg_Call {
	return &MockListProviderStream_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockListProviderStream_RecvMsg_Call) Run(run func(m interface{})) *MockListProviderStream_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockListProviderStream_RecvMsg_Call) Return(_a0 error) *MockListProviderStream_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListProviderStream_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *MockListProviderStream_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *MockListProviderStream) Send(_a0 *oauthcredentials.ListProvidersResponse) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*oauthcredentials.ListProvidersResponse) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListProviderStream_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockListProviderStream_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *oauthcredentials.ListProvidersResponse
func (_e *MockListProviderStream_Expecter) Send(_a0 interface{}) *MockListProviderStream_Send_Call {
	return &MockListProviderStream_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *MockListProviderStream_Send_Call) Run(run func(_a0 *oauthcredentials.ListProvidersResponse)) *MockListProviderStream_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*oauthcredentials.ListProvidersResponse))
	})
	return _c
}

func (_c *MockListProviderStream_Send_Call) Return(_a0 error) *MockListProviderStream_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListProviderStream_Send_Call) RunAndReturn(run func(*oauthcredentials.ListProvidersResponse) error) *MockListProviderStream_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *MockListProviderStream) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListProviderStream_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type MockListProviderStream_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockListProviderStream_Expecter) SendHeader(_a0 interface{}) *MockListProviderStream_SendHeader_Call {
	return &MockListProviderStream_SendHeader_Call{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *MockListProviderStream_SendHeader_Call) Run(run func(_a0 metadata.MD)) *MockListProviderStream_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockListProviderStream_SendHeader_Call) Return(_a0 error) *MockListProviderStream_SendHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListProviderStream_SendHeader_Call) RunAndReturn(run func(metadata.MD) error) *MockListProviderStream_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *MockListProviderStream) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListProviderStream_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockListProviderStream_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *MockListProviderStream_Expecter) SendMsg(m interface{}) *MockListProviderStream_SendMsg_Call {
	return &MockListProviderStream_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockListProviderStream_SendMsg_Call) Run(run func(m interface{})) *MockListProviderStream_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockListProviderStream_SendMsg_Call) Return(_a0 error) *MockListProviderStream_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListProviderStream_SendMsg_Call) RunAndReturn(run func(interface{}) error) *MockListProviderStream_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *MockListProviderStream) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockListProviderStream_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockListProviderStream_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockListProviderStream_Expecter) SetHeader(_a0 interface{}) *MockListProviderStream_SetHeader_Call {
	return &MockListProviderStream_SetHeader_Call{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *MockListProviderStream_SetHeader_Call) Run(run func(_a0 metadata.MD)) *MockListProviderStream_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockListProviderStream_SetHeader_Call) Return(_a0 error) *MockListProviderStream_SetHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockListProviderStream_SetHeader_Call) RunAndReturn(run func(metadata.MD) error) *MockListProviderStream_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *MockListProviderStream) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// MockListProviderStream_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type MockListProviderStream_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockListProviderStream_Expecter) SetTrailer(_a0 interface{}) *MockListProviderStream_SetTrailer_Call {
	return &MockListProviderStream_SetTrailer_Call{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *MockListProviderStream_SetTrailer_Call) Run(run func(_a0 metadata.MD)) *MockListProviderStream_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockListProviderStream_SetTrailer_Call) Return() *MockListProviderStream_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockListProviderStream_SetTrailer_Call) RunAndReturn(run func(metadata.MD)) *MockListProviderStream_SetTrailer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListProviderStream creates a new instance of MockListProviderStream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListProviderStream(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListProviderStream {
	mock := &MockListProviderStream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
